[build]
  command = "npm run build"
  publish = "dist/client"

# Specific redirect for dynamic argument routes
[[redirects]]
  from = "/a/*"
  to = "/a/index.html"
  status = 200

# General fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add caching headers for performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"